App/urls.py
#!python
# -*- coding: utf-8 -*-
# @Time    : 2019/6/7 12:59
# @Author  : 黄治文
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [

    # 主页路由
    url(r'^HomeVIew/$', views.HomeView.as_view(), name='HomeVIew'),
    # 商品展示路由
    url(r'^market$', views.market, name='market'),
    url(r'^MarketWithArgs/(?P<category_id>\d+)/(?P<child_cid>\d+)/(?P<sort_mode>\d+)',
        cache_page(60 * 2)(views.MarketWithArgsView.as_view()), name='MarketWithArgs'),
    # 购物车路由
    url(r'^CartPage/$', views.CartView.as_view(), name='CartPage'),
    url(r'^ChangeCart/(?P<operation>\d)/$',
        views.ChangeCartView.as_view(), name='ChangeCart'),
    url(r'^ChangeStatus/$',
        views.ChangeStatusView.as_view(),
        name='ChangeStatus'),
    url(r'^ChangeAllStatus/$',
        views.ChangeAllStatusView.as_view(),
        name='ChangeAllStatus'),
    url(r'^ChangeCartNum/$',
        views.ChangeCartNumView.as_view(),
        name='ChangeCartNum'),
    # 个人中心路由
    url(r'^Register/$', views.RegisterView.as_view(), name='Register'),
    url(r'^CheckUserId/$', views.CheckUserIdView.as_view(), name='CheckUserId'),
    url(r'^Login/$', views.Login.as_view(), name='Login'),
    url(r'^Mine/$', views.MineView.as_view(), name='Mine'),
    url(r'^Quit/$', views.QuitView.as_view(), name='Quit'),
    url(r'^out/$', views.out, name='out'),
    url(r'^Activate/', views.ActivateView.as_view(), name='Activate'),
    # 订单路由
    url(r'^AddOrder/$', views.AddOrderView.as_view(), name='AddOrder'),
    url(r'^OrderAjax/$', views.OrderAjaxView.as_view(), name='OrderAjax')
]

GPAXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^App/', include('App.urls', namespace='App'))

]

templates/main/cart.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/css/cart.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/js/cart.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="cart">
        <h3>Cart</h3>
        <div class="full">
            <section>
                <ul>
                    <li>收&nbsp;&nbsp;货&nbsp;&nbsp;人:&nbsp;Rock</li>
                    <li>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话:&nbsp;110</li>
                    <li>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址:&nbsp;宝盛里</li>
                </ul>

                <div class="bill">

                    <p>闪送超市</p>
                    <p>0元起送满30免运费22:00前可送达</p>
                    <a href="#">凑单专区</a>

                </div>

                <div class="delivery">
                    <span>收货时间</span>
                    <span>一小时内送达</span>
                    <a href="#">可预订&gt;</a>
                </div>

                <div class="delivery">
                    <span>收获备注</span>
                    <input type="text" placeholder="可输入100字以内的特殊要求">
                </div>

                <ul>
                    {% for Cart in carts %}
                        <li class="menuList" cartid="{{ Cart.id }}">
                            <div class="confirm">
                                <span cartid="{{ Cart.id }}">
                                    {% if Cart.if_selected %}
                                        <span>√</span>
                                        {% else %}
                                        <span></span>
                                    {% endif %}
                                </span>
                            </div>
                            <a href="#">
                                <img src="{{ cart.c_goods.productimg }}" alt="{{ Cart.c_goods.productlongname }}">
                                <p>{{ Cart.c_goods.productlongname }}</p>
                                <p class="presentPrice">{{ Cart.c_goods.price }}</p>
                            </a>


                            <section>
                                <button pID="{{Cart.c_goods.id}}" class="subShopping">-</button>
                                <span id="{{cart.c_goods.id}}">{{ Cart.goods_nums }}</span>
                                <button pID="{{Cart.c_goods.id}}" class="addShopping">+</button>
                            </section>

                        </li>
                    {% endfor %}

                </ul>

                <div class="payTheBill">
                    <div class="all_select">
                        <span>
                            {% if if_all_select %}
                                <span>√</span>
                                {% else %}
                                <span></span>
                            {% endif %}
                        </span>
                    </div>

                    <p>
                        <span style="font-size: 0.5rem">全选</span>
                        <span>共计:</span>
                        <span id="total_price">{{ total_price }}</span>
                    </p>

                    <a href="{% url 'App:addOrder' %}" id="make_order">下单</a>
                </div>

            </section>


        </div>
    </div>

{% endblock %}

templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base_main.html' %}
{% load static %}

{% block content %}
<div id="home">

<div class="swiper-container" id="topSwiper">
    <div class="swiper-wrapper" >
        {% for swiper_img in wheel_datas %}
        <div class="swiper-slide"><a><img src="{{ swiper_img.img }}" alt="{{ swiper_img.name }}"></a></div>
        {% endfor %}
    </div>
    <div class="swiper-pagination"></div><!--分页器。如果放置在swiper-container外面，需要自定义样式。-->

</div>
<div class="topMenu">
    <nav>
        <ul>
            {% for nav_data in nav_datas %}
                <li><img src="{{ nav_data.img }}" alt="{{ nav_data.name }}"></li>
            {% endfor %}
        </ul>
    </nav>

</div>
<div class="swiper-container" id="swiperMenu">
    <ul class="swiper-wrapper" >
        {% for must_buy_data in must_buy_datas%}
        <li class="swiper-slide"><img src="{{ must_buy_data.img }}"></li>
        {% endfor %}
    </ul>
    <div class="swiper-pagination"></div><!--分页器。如果放置在swiper-container外面，需要自定义样式。-->

</div>
<div class="CVS">
    <h2>
        <img src="{{ shop0_1_datas.0.img }}" alt="{{ shop0_1_datas.0.name }}">
    </h2>
    <fieldset>
        {% for shop1_3_data in shop1_3_datas %}

        <a><img src="{{ shop1_3_data.img }}" alt="{{ shop1_3_data.name }}"></a>
        {% endfor %}
    </fieldset>
    <ul>
        {% for shop3_7_data in shop3_7_datas %}
        <li>
            <img src="{{ shop3_7_data.img }}" alt="{{ shop3_7_data.name }}">
        </li>
        {% endfor %}
    </ul>
    <ol>
        {% for shop7_11_data in shop7_11_datas %}
        <li>
            <a href="#"><img src="{{ shop7_11_data.img }}" alt="{{ shop7_11_data.name }}"></a>
        </li>
        {% endfor %}
    </ol>
</div>
    <div class="mainInfo">
        {% for mainshow_data in mainshow_datas %}
        <section>
            <h3>
                {{ mainshow_data.name }}
                <a href="#"></a>
                <span></span>
            </h3>

        </section>

        <div>
            <a><img src="{{ mainshow_data.img }}" alt="{{ mainshow_data.name }}"></a>
        </div>
        <section>
            <ul>

                <li>
                    <a>
                        <img src="{{ mainshow_data.img1 }}">


                    </a>
                    <p class="discription">{{ mainshow_data.longname1 }}</p>
                    <a>
                        <span>{{ mainshow_data.price1 }}</span>
                        <s>{{ mainshow_data.marketprice1 }}</s>
                    </a>
                    <button>
                        <span>+</span>
                    </button>
                </li>
                <li>
                    <a>
                        <img src="{{ mainshow_data.img2 }}">


                    </a>
                    <p class="discription">{{ mainshow_data.longname2 }}</p>
                    <a>
                        <span>{{ mainshow_data.price2 }}</span>
                        <s>{{ mainshow_data.marketprice2 }}</s>
                    </a>
                    <button>
                        <span>+</span>
                    </button>
                </li>
                <li>
                    <a>
                        <img src="{{ mainshow_data.img3 }}">


                    </a>
                    <p class="discription">{{ mainshow_data.longname3 }}</p>
                    <a>
                        <span>{{ mainshow_data.price3 }}</span>
                        <s>{{ mainshow_data.marketprice3 }}</s>
                    </a>
                    <button>
                        <span>+</span>
                    </button>
                </li>
            </ul>
        </section>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block ext_css %}
{{ block.super }}

<link rel="stylesheet" href="{% static 'axf/css/home.css' %}">

{% endblock %}
{% block ext_js %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'axf/js/home.js' %}"></script>


{% endblock %}

</body>
</html>

templates/main/market.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
{% extends 'base_main.html'%}
{% load static %}
{% block content %}
<div id="market">
    <aside>
        <menu>

            <ul>

                {% for type_data in type_datas %}

                <li class="aside">
                    <span class="yellowSlide"></span>
                    <a href="/App/market_with_arg/{{ type_data.typeid }}/0/{{ sort_mode }}">{{ type_data.typename }}</a>
                </li>
                {% endfor %}
            </ul>
        </menu>
    </aside>
    <!--    context = {
            'title': title,
            'type_datas': type_datas,
            'goods_type_datas': goods_type_datas,
            'child_category_datas': child_category_datas,
            'goods_by_childcid_datas': goods_by_childcid_datas

        }-->
    <nav>
        <ul>

            <li><span id="alltypebtn">全部类型<span class="glyphicon glyphicon-chevron-down"></span></span></li>
            <li><span id="showsortbtn">综合排序<span class="glyphicon glyphicon-chevron-down"></span></span></li>

        </ul>
    </nav>
    <div>
        <section>
            <menu>
                <ul>
                    {% for goods_data in goods_datas %}
                    <li>
                        <a href="#">
                            <img src="{{goods_data.productimg}}"/>
                            <div class="shoppingInfo">
                                <h6>{{goods_data.productlongname}}</h6>
                                <p class="detailTag"><span>精选</span><span>{{goods_data.pedesc}}</span></p>
                                <span class="unit">{{goods_data.specifics}}</span>
                                <p class="price">
                                    <span>￥{{goods_data.price}}</span><s><span>￥{{goods_data.marketprice}}</span></s>
                                </p>
                            </div>
                        </a>
                        <section>
                            <button pID="{{goods_data.id}}" class="subShopping">-</button>
<!--                            <span id="{{item.productid}}">{{item.num|default:0}}</span>-->

<!--                            <span id="{{ goods_data.id }}">{{ goods_data.se }}</span>-->

                            <span id="{{ goods_data.id }}" class="num">0</span>
                            <button pID="{{goods_data.id}}" class="addShopping">+</button>
                        </section>

                    </li>
                    {% endfor %}
                </ul>

                <div id="typediv">
                    <div>
                        {% for child_category_data in child_category_datas %}
                        <a href="{% url 'App:market_with_arg' categoryid child_category_data.1 sort_mode %}"><span>{{ child_category_data.0 }}</span></a>
                        {% endfor %}
                    </div>
                </div>
                <div id="sortdiv">
                    <div>
                        <a href="/App/market_with_arg/{{categoryid}}/{{childcid}}/0/"
                           class="sorta"><span>综合排序</span></a>
                        <a href="{% url 'App:market_with_arg' categoryid childcid 1 %}" class="sorta"><span>销量排序</span></a>
                        <a href="/App/market_with_arg/{{categoryid}}/{{childcid}}/2/"
                           class="sorta"><span>价格最低</span></a>
                        <a href="/App/market_with_arg/{{categoryid}}/{{childcid}}/3/"
                           class="sorta"><span>价格最高</span></a>

                    </div>
                </div>
            </menu>
        </section>

    </div>

</div>
{% endblock content%}
{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'axf/css/market_with_arg.css' %}">
{% endblock ext_css %}
{% block ext_js %}
{{ block.super }}
<script type="text/javascript" src="{% static 'axf/js/market_with_arg.js' %}"></script>
{% endblock ext_js%}
</body>
</html>

templates/main/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'base_main.html' %}
{% load static %}
{% block content %}
<h1><span class="username">{{ username }}</span></h1>
<!--<a href="{% url 'App:out' %}"><span class="out">退出登录</span></a>-->
<p><span class="out">退出登陆</span></p>
{% endblock content %}
{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'axf/css/mine.css' %}">
{% endblock ext_css %}
{% block ext_js %}
{{ block.super }}
<script type="text/javascript" src="{% static 'axf/js/mine.js' %}"></script>
{% endblock ext_js %}
</body>
</html>