App/urls.py
#!python
# -*- coding: utf-8 -*-
# @Time    : 2019/6/7 12:59
# @Author  : 黄治文
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [

    # 主页路由
    url(r'^HomeVIew/$', views.HomeView.as_view(), name='HomeVIew'),
    # 商品展示路由
    url(r'^market$', views.market, name='market'),
    url(r'^MarketWithArgs/(?P<category_id>\d+)/(?P<child_cid>\d+)/(?P<sort_mode>\d+)',
        cache_page(60 * 2)(views.MarketWithArgsView.as_view()), name='MarketWithArgs'),
    # 购物车路由
    url(r'^CartPage/$', views.CartView.as_view(), name='CartPage'),
    url(r'^ChangeCart/(?P<operation>\d)/$',
        views.ChangeCartView.as_view(), name='ChangeCart'),
    url(r'^ChangeStatus/$',
        views.ChangeStatusView.as_view(),
        name='ChangeStatus'),
    url(r'^ChangeAllStatus/$',
        views.ChangeAllStatusView.as_view(),
        name='ChangeAllStatus'),
    url(r'^ChangeCartNum/$',
        views.ChangeCartNumView.as_view(),
        name='ChangeCartNum'),
    # 个人中心路由
    url(r'^Register/$', views.RegisterView.as_view(), name='Register'),
    url(r'^CheckUserId/$', views.CheckUserIdView.as_view(), name='CheckUserId'),
    url(r'^Login/$', views.Login.as_view(), name='Login'),
    url(r'^Mine/$', views.MineView.as_view(), name='Mine'),
    url(r'^Quit/$', views.QuitView.as_view(), name='Quit'),
    url(r'^out/$', views.out, name='out'),
    url(r'^Activate/', views.ActivateView.as_view(), name='Activate'),
    # 订单路由
    url(r'^AddOrder/$', views.AddOrderView.as_view(), name='AddOrder'),
    url(r'^OrderAjax/$', views.OrderAjaxView.as_view(), name='OrderAjax')
]

GPAXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^App/', include('App.urls', namespace='App'))

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maxmum-scale=1,userscalable=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    {% block ext_css %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block ext_js %}
{% endblock %}

</body>
</html>

templates/base_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'axf/css/main.css'%}">
{% endblock%}
{% block header %}
<header></header>
{% endblock %}
{% block content %}
{% endblock content%}
{% block footer %}
<footer>
    <a href="{% url 'App:home' %}" class="home">
        <dl>
            <dt><span></span></dt>
            <dd>首页</dd>
        </dl>
    </a>
    <a href="{% url 'App:market' %}" class="market">
        <dl>
            <dt><span></span></dt>
            <dd>闪购</dd>
        </dl>
    </a>
    <a href="{% url 'App:cart_fun' %}" class="cart">
        <dl>
            <dt><span></span></dt>
            <dd>购物车</dd>
        </dl>
    </a>
    <a href="{% url 'App:mine' %}" class="mine">
        <dl>
            <dt><span></span></dt>
            <dd>我的</dd>
        </dl>
    </a>


</footer>
{% endblock %}
</body>
</html>

templates/base_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% load static %}

</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ test1 }}</h1>

</body>